name: bday_reminder
dependencies:
  - python=3.10
  - pip
  - pip:
      - twilio==6.63.2
      - python-dotenv==0.20.0
      - openpyxl==3.0.7
      - pandas==1.5.3
      - psycopg2-binary==2.9.6
      - Jinja2==3.1.2